openapi: 3.0.3
info:
  title: Employee service
  description: Service for hiring and firing employees
  version: 1.0.0
servers:
  - url: 'https://localhost:8000/api/v1'
tags:
  - name: Employee
    description: Endpoints for hiring and firing employees from organizations
paths:
  /orgmanager/fire/all/{id}:
    delete:
      summary: Fire all employees from an organization with specified ID
      description: Fire all employees from an organization with specified ID
      operationId: fireAllEmployeesFromOrganization
      tags: [Employee]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
            exclusiveMinimum: false
            example: 4
      responses:
        200:
          description: All employees have been fired from organization
        default:
          $ref: '#/components/responses/ErrorResponse'


  /orgmanager/hire/{id}:
    post:
      summary: Add a new employee to and organization with a specified ID
      description: Add a new employee to and organization with a specified ID
      operationId: addNewEmployeeToOrganization
      tags: [Employee]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
            exclusiveMinimum: false
            example: 4
      responses:
        200:
          description: A new employee has been added to organization
        default:
          $ref: '#/components/responses/ErrorResponse'

components:
  responses:
    ErrorResponse:
      description: Error
      content:
        application/xml:
          schema:
            type: object
            xml:
              name: error
            properties:
              code:
                type: string
                description: Error identifier
                example: invalid_parameters
              message:
                type: string
                description: Human-readable message
                example: Invalid parameters supplied
              time:
                type: string
                format: date-time
                example: 2023-09-18T00:00:09Z

